[env:esp32-s3-dev]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
upload_speed = 921600
build_type = release


build_flags =
  -DPSRAM_ENABLE=1
  -DCORE_DEBUG_LEVEL=5
