[env:esp32-s3-dev]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1  ; Different S3 variant

framework = espidf
monitor_speed = 115200

; EVITAR MSYS2 - Usar toolchain de PlatformIO
build_src_filter = +<main.cpp> -<*>


[env:scr_test]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_src_filter =
    +<scr_test.cpp>   ; usa solo este archivo
    -<*>            ; excluye los demás
